# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jamie Collins
author: James R. Collins
email: james.r.collins@aya.yale.edu
description: > # this means to ignore newlines until "baseurl:"
    Personal website of Jamie Collins, Ph.D. student in chemical oceanography at the Massachusetts Institute of Technology (MIT) and Woods Hole Oceanographic Institution (WHOI). Research interests include lipid geochemistry, lipidomics, sources and effects of oxidative stress in marine microorganisms, mechanisms through which organic matter is oxidized in the surface ocean, and development of new instruments for making observations in the marine environment.
baseurl: "" # the subpath of your site, e.g. /blog
url: “http://localhost:4000” # the base hostname & protocol for your site
twitter_username: jamesrco
github_username:  jamesrco

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM